# Cổng mặc định cho Config Server
server.port=8888
# Đường dẫn đến kho Git chứa file cấu hình (chúng ta sẽ tạo nó ở bước 
# sau)
spring.cloud.config.server.git.uri=file://${user.home}/microservice-configs
